[package]
name = "bitski-chain-models"
version = "0.2.5"
edition = "2021"
description = "Data for Bitski Rust SDK"
license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
